from typing import Any
from pyracmon import Model, CRUDMixin
from pyracmon.model_graph import GraphEntityMixin
from pyracmon.stub import ModelTransform
from pyracmon.testing import TestingMixin
from pyracmon.dialect.postgresql import PostgreSQLMixin
from datetime import time, date, timedelta, datetime
from uuid import UUID
from typing import Any

class t1(PostgreSQLMixin, TestingMixin, CRUDMixin, GraphEntityMixin, ModelTransform, Model):
    c11: int = ...
    c12: int = ...
    c13: str = ...

class t2(PostgreSQLMixin, TestingMixin, CRUDMixin, GraphEntityMixin, ModelTransform, Model):
    c21: int = ...
    c22: int = ...
    c23: str = ...

class t3(PostgreSQLMixin, TestingMixin, CRUDMixin, GraphEntityMixin, ModelTransform, Model):
    c31: int = ...
    c32: int = ...
    c33: str | None = ...

class t4(PostgreSQLMixin, TestingMixin, CRUDMixin, GraphEntityMixin, ModelTransform, Model):
    c41: int = ...
    c42: int = ...
    c43: int = ...

class types(PostgreSQLMixin, TestingMixin, CRUDMixin, GraphEntityMixin, ModelTransform, Model):
    bool_: bool | None = ...
    double_: float | None = ...
    int_: int | None = ...
    string_: str | None = ...
    bytes_: bytes | None = ...
    date_: date | None = ...
    datetime_: datetime | None = ...
    time_: time | None = ...
    delta_: timedelta | None = ...
    uuid_: UUID | None = ...
    enum_: Any | None = ...
    record_: Any | None = ...
    array_: list[int] | None = ...
    deeparray_: list[int] | None = ...
    json_: Any | None = ...
    jsonb_: Any | None = ...

class v1(PostgreSQLMixin, TestingMixin, CRUDMixin, GraphEntityMixin, ModelTransform, Model):
    c11: int | None = ...
    c12: int | None = ...
    c31: int | None = ...
    c32: int | None = ...

class mv1(PostgreSQLMixin, TestingMixin, CRUDMixin, GraphEntityMixin, ModelTransform, Model):
    c11: int | None = ...
    c12: int | None = ...
    c31: int | None = ...
    c32: int | None = ...

class mv2(PostgreSQLMixin, TestingMixin, CRUDMixin, GraphEntityMixin, ModelTransform, Model):
    bool_: bool | None = ...
    double_: float | None = ...
    int_: int | None = ...
    string_: str | None = ...
    bytes_: bytes | None = ...
    date_: date | None = ...
    datetime_: datetime | None = ...
    time_: time | None = ...
    delta_: timedelta | None = ...
    uuid_: UUID | None = ...
    enum_: Any | None = ...
    record_: Any | None = ...
    array_: list[int] | None = ...
    deeparray_: list[int] | None = ...
    json_: Any | None = ...
    jsonb_: Any | None = ...
