"""
This module provides a type that specifies the structure of a graph.
"""
from typing import Any, Callable, overload, Self
from collections.abc import Iterable, Iterator
from .identify import IdentifyPolicy, neverPolicy


type PropDef[_PT] = tuple[type[_PT] | GraphTemplate | GraphTemplate.Property, IdentifyPolicy | None, Callable[[_PT], bool] | None]


class GraphTemplate:
    """
    This class represents the structure of a graph.

    The template is composed of template properties, each of which corresponds to a node container in a graph.
    Each template property is accessible as an attribute of the template, named after the property.

    Applying a shift operator between properties creates a parent-child relationship between them.
    In the following code, the template is composed of four properties, where `d` is a child of `c`, and `b` and `c` are children of `a`.

    ```python
    template = GraphSpec().new_template(a=int, b=str, c=int, d=float)
    template.a << [template.b, template.c]
    template.c << template.d
    ```

    Templates are merged when `+` is applied to them. The result has the properties defined in both templates, with their relationships preserved.
    Merging templates that have properties with the same name raises a `ValueError`.

    Use `GraphSpec.new_template` or other factory functions to create a template, instead of using the constructor directly.
    """
    class Property[T]:
        """
        A template property that determines various behaviors of graph nodes.
        """
        def __init__(
            self,
            template: 'GraphTemplate',
            name: str,
            kind: 'type[T] | GraphTemplate',
            policy: IdentifyPolicy,
            entity_filter: Callable[[T], bool] | None,
            *,
            origin: Self | None = None,
            nested: bool = False,
        ):
            #: The graph template this property belongs to.
            self.template = template
            #: The name of the property.
            self.name = name
            #: The entity type of this property. It can be a primitive type or another template.
            self.kind = kind
            #: The policy used for entity identification.
            self.policy = policy
            #: The entity filter function, if any.
            self.entity_filter = entity_filter
            self._origin = origin
            self._nested = nested

        def _assert_canbe_parent(self, another: 'GraphTemplate.Property'):
            if another.parent is not None:
                raise ValueError(f"Graph template property can not have multiple parents.")
            if self.template != another.template:
                raise ValueError(f"Properties can make parent-child relationship only when they are declared in the same template.")
            if self == another:
                raise ValueError(f"Recursive relationship is not allowed.")
            if isinstance(self.kind, GraphTemplate):
                raise ValueError(f"Property for graph template can't have child.")
            p = self
            while p.parent is not None:
                if p.parent == another:
                    raise ValueError(f"Recursive relationship is not allowed.")
                p = p.parent

        @property
        def key(self) -> str:
            """
            Returns the key of this property used when the graph is serialized into a dictionary.

            TODO
            The joining method is implemented in graph.Nest class.
            There should be an explicit association between joining and splitting methods somewhere.
            """
            return self.name.split('.')[-1] if self._nested else self.name

        @property
        def parents(self) -> 'Iterable[GraphTemplate.Property]':
            """
            Returns all parent properties.
            """
            return map(lambda r: r[1], filter(lambda r: r[0] == self, self.template._relations))

        @property
        def parent(self) -> 'GraphTemplate.Property | None':
            """
            Returns the parent property, if one exists.
            """
            return next(iter(self.parents), None)

        @property
        def children(self) -> 'list[GraphTemplate.Property]':
            """
            Returns the child properties.
            """
            return [r[0] for r in self.template._relations if r[1] == self]

        @property
        def origin(self) -> 'GraphTemplate.Property':
            """
            Returns the original property in the property chain generated by adding templates.
            """
            p = self
            while p._origin:
                p = p._origin
            return p

        def is_compatible(self, other):
            return self.origin is other.origin

        def _move_template(self, dest: 'GraphTemplate', new_name=None) -> 'GraphTemplate.Property':
            """
            Copies this property and its children, setting their template to `dest`.
            """
            new_name = new_name or self.name
            prop = GraphTemplate.Property(dest, new_name, self.kind, self.policy, self.entity_filter, origin=self)
            _set_template_property(dest, prop)
            for c in self.children:
                cc = c._move_template(dest)
                _ = prop << cc
            return prop

        @overload
        def __lshift__(self, children: 'GraphTemplate.Property') -> 'GraphTemplate.Property': ...
        @overload
        def __lshift__(self, children: 'list[GraphTemplate.Property]') -> 'list[GraphTemplate.Property]': ...
        def __lshift__(self, children: 'GraphTemplate.Property | list[GraphTemplate.Property]') -> 'GraphTemplate.Property | list[GraphTemplate.Property]':
            """
            Makes this property the parent of the given properties.

            Args:
                children: A property, or a list of properties, to become children of this property.
            Returns:
                The same object passed as `children`.
            """
            targets = [children] if isinstance(children, GraphTemplate.Property) else children
            for c in targets:
                self._assert_canbe_parent(c)
            self.template._relations += [(c, self) for c in targets]
            return children

        def __rshift__(self, parent: 'GraphTemplate.Property') -> 'GraphTemplate.Property':
            """
            Makes this property a child of another property.

            Args:
                parent: The property to become the parent of this property.
            Returns:
                The same object passed as `parent`.
            """
            parent._assert_canbe_parent(self)
            self.template._relations += [(self, parent)]
            return parent

        def __rrshift__(self, children: 'GraphTemplate.Property | list[GraphTemplate.Property]') -> 'GraphTemplate.Property':
            """
            The reversed version of `__lshift__()`, provided so that a list of properties can appear on the left-hand side of the operator.

            Args:
                children: A property, or a list of properties, to become children of this property.
            Returns:
                This property.
            """
            self.__lshift__(children)
            return self

    def __init__(self, definitions: 'list[tuple[str, *PropDef]]', nested: bool = False):
        """
        Initializes the template with the given properties. Don't use this constructor directly.

        Args:
            definitions: The definitions of the template's properties.
            nested: Whether properties of this template have nested names.
        """
        self._properties: dict[str, GraphTemplate.Property] = {}
        self._relations: list[tuple[GraphTemplate.Property, GraphTemplate.Property]] = []
        self._nested = nested

        for d in definitions:
            name, kind, ident, ef = d

            ident = ident or neverPolicy()

            if isinstance(kind, GraphTemplate):
                prop = GraphTemplate.Property(self, name, kind, ident, None, nested=kind._nested)
                _set_template_property(self, prop)
            elif isinstance(kind, GraphTemplate.Property):
                kind._move_template(self, name)
            else:
                _set_template_property(self, GraphTemplate.Property(self, name, kind, ident, ef, nested=self._nested))

    def __getattr__(self, key) -> 'GraphTemplate.Property':
        return self._properties[key]

    def __getitem__(self, key) -> 'GraphTemplate.Property':
        return self._properties[key]

    def __iter__(self) -> 'Iterator[GraphTemplate.Property]':
        """
        Iterates the properties in parent-to-child order.

        Returns:
            An iterator over the properties.
        """
        return _walk_properties(self._properties)

    def __iadd__(self, another: 'GraphTemplate') -> Self:
        """
        Adds another template to this template.

        Args:
            another: The template to add.
        Returns:
            This instance.
        """
        if self._nested != another._nested:
            raise ValueError(f"Graphs with different nested settings cannot be merged.")

        for p in another._properties.values():
            prop = GraphTemplate.Property(self, p.name, p.kind, p.policy, p.entity_filter, origin=p, nested=p._nested)
            _set_template_property(self, prop)

        for n, p in another._relations:
            _ = getattr(self, n.name) >> getattr(self, p.name)

        return self

    def __add__(self, another: 'GraphTemplate') -> 'GraphTemplate':
        """
        Creates a new template by merging this template with another.

        Args:
            another: The template to merge with this one.
        Returns:
            The merged template.
        """
        template = GraphTemplate([], nested=self._nested)
        template += self
        template += another

        return template


def _set_template_property(template: GraphTemplate, prop: GraphTemplate.Property):
    if prop._nested != template._nested:
        raise ValueError(f"Nested property setting of templates must be the same to add them.")
    if prop.name in template._properties:
        raise ValueError(f"Property name '{prop.name}' conflicts.'")
    template._properties[prop.name] = prop


def _walk_properties(properties: dict[str, GraphTemplate.Property], parent: GraphTemplate.Property | None = None):
    def walk(p):
        yield p
        for q in p.children:
            for r in walk(q):
                yield r

    for p in filter(lambda p: p.parent is parent, properties.values()):
        for q in walk(p):
            yield q