version: '3'
services:
  pyracmon:
    build:
      context: ./Dockerfiles
      dockerfile: python3.7
    image: pyracmon:develop
    tty: true
    volumes:
      - .:/home/pyracmon
    container_name: pyracmon
  pyracmon3.6:
    build:
      context: ./Dockerfiles
      dockerfile: python3.6
    image: pyracmon3.6:develop
    tty: true
    volumes:
      - .:/home/pyracmon
    container_name: pyracmon-3.6
  pyracmon3.8:
    build:
      context: ./Dockerfiles
      dockerfile: python3.8
    image: pyracmon3.8:develop
    tty: true
    volumes:
      - .:/home/pyracmon
    container_name: pyracmon-3.8
  pyracmon3.9:
    build:
      context: ./Dockerfiles
      dockerfile: python3.9
    image: pyracmon3.9:develop
    tty: true
    volumes:
      - .:/home/pyracmon
    container_name: pyracmon-3.9
  postgres:
    image: postgres:10
    ports:
      - 35432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/postgres
    volumes:
      - pyracmon_postgres:/var/lib/postgresql/data/postgres
      - ./postgresql/initdb.d:/docker-entrypoint-initdb.d
    container_name: pyracmon_postgres
  mysql:
    image: mysql:8
    ports:
      - 33306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - pyracmon_mysql:/var/lib/mysql
      - ./mysql/initdb.d:/docker-entrypoint-initdb.d
      - ./mysql/conf.d:/etc/mysql/conf.d
volumes:
  pyracmon_postgres:
  pyracmon_mysql:
