version: '3'
services:
  pyracmon:
    build: .
    image: pyracmon:develop
    tty: true
    volumes:
      - .:/home/pyracmon
    container_name: pyracmon
  postgres:
    image: postgres:10
    ports:
      - 35432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/postgres
    volumes:
      - pyracmon_postgres:/var/lib/postgresql/data/postgres
      - ./postgresql/initdb.d:/docker-entrypoint-initdb.d
    container_name: pyracmon_postgres
  mysql:
    image: mysql:8
    ports:
      - 33306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - pyracmon_mysql:/var/lib/mysql
      - ./mysql/initdb.d:/docker-entrypoint-initdb.d
      - ./mysql/conf.d:/etc/mysql/conf.d
volumes:
  pyracmon_postgres:
  pyracmon_mysql:
