from typing import Any
from pyracmon import Model, CRUDMixin, AsyncCRUDMixin
from pyracmon.model_graph import GraphEntityMixin
from pyracmon.stub import ModelTransform
from pyracmon.testing import TestingMixin, AsyncTestingMixin
from pyracmon.dialect.postgresql import AsyncPostgreSQLMixin

class blog(AsyncPostgreSQLMixin, AsyncTestingMixin, AsyncCRUDMixin, GraphEntityMixin, ModelTransform, Model):
    id: int = ...
    title: str = ...

class blog_category(AsyncPostgreSQLMixin, AsyncTestingMixin, AsyncCRUDMixin, GraphEntityMixin, ModelTransform, Model):
    id: int = ...
    blog_id: int = ...
    name: str = ...

class image(AsyncPostgreSQLMixin, AsyncTestingMixin, AsyncCRUDMixin, GraphEntityMixin, ModelTransform, Model):
    post_id: int = ...
    url: str = ...

class post(AsyncPostgreSQLMixin, AsyncTestingMixin, AsyncCRUDMixin, GraphEntityMixin, ModelTransform, Model):
    id: int = ...
    blog_id: int = ...
    title: str = ...
    content: str = ...

class post_comment(AsyncPostgreSQLMixin, AsyncTestingMixin, AsyncCRUDMixin, GraphEntityMixin, ModelTransform, Model):
    id: int = ...
    post_id: int = ...
    likes: int = ...
    content: str = ...
