"""
This module provides interfaces defined in DB-API 2.0.
"""
from collections.abc import Sequence, Generator, AsyncGenerator
from contextlib import contextmanager, asynccontextmanager
from typing import Protocol, Any


class Cursor(Protocol):
    @property
    def description(self) -> str: ...
    @property
    def rowcount(self) -> int: ...
    @property
    def arraysize(self) -> int: ...

    #def callproc(self, procname: str, *args, **kwargs) -> Any: ...
    #def nextset(self) -> bool: ...
    def close(self) -> None: ...
    def execute(self, operation: str, *args, **kwargs) -> Any: ...
    def executemany(self, operation: str, seq_of_parameters: Sequence[Any]) -> Any: ...
    def fetchone(self) -> Sequence[Any] | None: ...
    def fetchmany(self, size: int = 0) -> Sequence[Sequence[Any]]: ...
    def fetchall(self) -> Sequence[Sequence[Any]]: ...
    def setinputsizes(self, sizes: Sequence[Any]): ...
    def setoutputsize(self, size: int, column: int): ...


class Connection(Protocol):
    def close(self) -> None: ...
    def commit(self) -> None: ...
    def rollback(self) -> None: ...
    def cursor(self) -> Cursor: ...


class AsyncCursor(Protocol):
    @property
    def description(self) -> str: ...
    @property
    def rowcount(self) -> int: ...
    @property
    def arraysize(self) -> int: ...

    #def callproc(self, procname: str, *args, **kwargs) -> Any: ...
    #def nextset(self) -> bool: ...
    async def close(self) -> None: ...
    async def execute(self, operation: str, *args, **kwargs) -> Any: ...
    async def executemany(self, operation: str, seq_of_parameters: Sequence[Any]) -> Any: ...
    async def fetchone(self) -> Sequence[Any] | None: ...
    async def fetchmany(self, size: int = 0) -> Sequence[Sequence[Any]]: ...
    async def fetchall(self) -> Sequence[Sequence[Any]]: ...
    async def setinputsizes(self, sizes: Sequence[Any]): ...
    async def setoutputsize(self, size: int, column: int): ...


class AsyncConnection(Protocol):
    async def close(self) -> None: ...
    async def commit(self) -> None: ...
    async def rollback(self) -> None: ...
    def cursor(self) -> AsyncCursor: ...


@contextmanager
def cursor(c: Cursor) -> Generator[Cursor, None, None]:
    try:
        yield c
    finally:
        c.close()


@asynccontextmanager
async def acursor(c: AsyncCursor) -> AsyncGenerator[AsyncCursor, None]:
    try:
        yield c
    finally:
        await c.close()