"""
This module provides a mixin type that supplies various DB operations to model types as class methods.
"""
from collections.abc import Mapping, Sequence
from functools import reduce
from typing import Any, TypeVar, Literal, cast, overload, TYPE_CHECKING
from .connection import Connection
from .model import Column, IModel, Record, parse_pks, check_columns, model_values, extract_pks
from .select import SelectMixin, AliasedColumn, read_row
from .query import Q, Expression, Conditional, where
from .clause import ORDER, ranged_by, order_by, values
from .util import key_to_index, Qualifier, PKS


if TYPE_CHECKING:
    class CRUDMixinBase(IModel):
        @classmethod
        def last_sequences(cls, db: Connection, num: int) -> list[tuple[Column, int]]:
            """
            Returns the sequential (auto-incremental) values of a table generated by the latest insertion.

            The result contains all sequential columns and their values.
            When the latest query inserts multiple rows, only the last (i.e., largest) value is returned.

            This method should be overridden by another mixin class defined in a `dialect` module.

            Args:
                db: The DB connection.
                num: The number of records inserted by the latest query.
            Returns:
                A list of `(column, value)` pairs.
            """
            ...

        @classmethod
        def support_returning(cls, db: Connection) -> bool:
            """
            Checks whether this DBMS supports the **RETURNING** clause.

            Args:
                db: The DB connection.
            Returns:
                Whether this DBMS supports the **RETURNING** clause.
            """
            ...
else:
    class CRUDMixinBase:
        pass


M = TypeVar('M', bound='CRUDMixin')
C = TypeVar('C', bound=str | AliasedColumn, covariant=True)


class CRUDMixin(SelectMixin, CRUDMixinBase):
    """
    The default mixin providing class methods available on all model types.

    Every method takes the DB connection object as its first argument.
    Several methods take the following arguments.

    - `pks`
        - Primary key value(s).
        - A single value is available for a model whose table has just one primary key column.
        - e.g., if the table has a single primary key `id` of type `int`, `1` can be used to specify the row where `id = 1`.
        - e.g., if the table has multiple primary keys `intid` and `strid`, `dict(intid=1, strid="abc")` is a valid argument.
    - `record` / `records`
        - A record can be a model object or a mapping from column names to their values.
        - Only the columns contained in the record are affected by the operation.
        - e.g., when `dict(c1=1, c2="abc")` is passed for insertion, only `c1` and `c2` are set in the INSERT query.
        - e.g., for an UPDATE query, only those columns will be updated.
    - `condition`
        - A query condition that composes the WHERE clause.
        - `pyracmon.query.Q` is a factory class for creating condition objects.
        - When `None` is passed, all rows are subject to the operation.
    - `qualifier`
        - A mapping from column names to functions that qualify their placeholder markers.
        - Details about the qualifier function are described below.
    - `lock`
        - This is a reserved argument for a locking statement, but currently it just works as a postfix appended to the query.
        - The usage will be changed in a future version.

    The qualifier function is typically used to convert or replace a placeholder marker in an INSERT or UPDATE query.
    By default, those queries contain markers like `INSERT INTO t (c1, c2) VALUES (?, ?)` (the `qmark` paramstyle).
    We sometimes need to qualify markers to apply a DB function, a calculation, a type cast, and so on.
    This feature makes that possible, as shown below.

    ```python
    t.insert(db, dict(c1=1, c2=None), dict(c1=lambda x: f"{x}+1", c2=lambda x: "now()"))
    # SQL: INSERT INTO t (c1, c2) VALUES (?+1, now())
    ```
    """
    @classmethod
    def count(cls, db: Connection, condition: Conditional = Q.of()) -> int:
        """
        Count the rows that satisfy the condition.

        ```python
        t.count(db, Q.eq(c1=1))
        # SQL: SELECT COUNT(*) FROM t WHERE c1 = 1
        ```

        Args:
            db: The DB connection.
            condition: The query condition.
        Returns:
            The number of rows.
        """
        wc, wp = where(condition)
        c = db.stmt().execute(f"SELECT COUNT(*) FROM {cls.name}{_spacer(wc)}", *wp)
        return c.fetchone()[0] # type: ignore

    @classmethod
    def fetch(cls: type[M], db: Connection, pks: PKS, lock: Any | None = None) -> M | None:
        """
        Fetch a record by primary key(s).

        ```python
        t.fetch(db, 1)
        # SQL: SELECT * FROM t WHERE id = 1
        ```

        Args:
            db: The DB connection.
            pks: The primary key value(s).
            lock: A locking statement.
        Returns:
            A model object if it exists, otherwise `None`.
        """
        cols, vals = parse_pks(cls, pks)
        cond = Conditional.all([Q.eq(**{c: v}) for c, v in zip(cols, vals)])
        wc, wp = where(cond)
        s = cls.select()
        c = db.stmt().execute(f"SELECT {s} FROM {cls.name}{_spacer(wc)}{_spacer(lock)}", *wp)
        row = c.fetchone()
        return read_row(row, *s)[0] if row else None

    @classmethod
    def fetch_many(cls: type[M], db: Connection, seq_pks: Sequence[PKS], lock: Any | None = None, /, per_page: int = 1000) -> list[M]:
        """
        Fetch records by a sequence of primary key(s).

        This method simply concatenates equality conditions on the primary key(s) using the OR operator.

        ```python
        t.fetch_many(db, [1, 2, 3])
        # SQL: SELECT * FROM t WHERE id = 1 OR id = 2 OR id = 3
        ```

        Args:
            db: The DB connection.
            seq_pks: A sequence of primary key value(s).
            lock: A locking statement.
            per_page: The maximum number of keys per query execution.
        Returns:
            The model objects, in the same order as the given sequence.
        """
        res = []
        index = 0
        while index < len(seq_pks):
            ordered_pks = []
            cond = Q.of()
            for pks in seq_pks[index:index+per_page]:
                cols, vals = parse_pks(cls, pks)
                ordered_pks.append(tuple(v for v in vals))
                cond |= Conditional.all([Q.eq(**{c: v}) for c, v in zip(cols, vals)])
            wc, wp = where(cond)
            s = cls.select()
            c = db.stmt().execute(f"SELECT {s} FROM {cls.name}{_spacer(wc)}{_spacer(lock)}", *wp)

            record_map = {}
            for r in [read_row(row, *s)[0] for row in c.fetchall()]:
                pk_values = {c.name:v for c, v in r if c.pk}
                record_map[tuple([v for _, v in check_columns(cls, pk_values, lambda c: c.pk, True)])] = r

            res.extend([record_map[k] for k in ordered_pks if k in record_map])
            index += per_page

        return res

    @classmethod
    def fetch_where(
        cls: type[M],
        db: Connection,
        condition: Conditional = Q.of(),
        orders: Mapping[C, ORDER] = {},
        limit: int | None = None,
        offset: int | None = None,
        lock: Any | None = None,
    ) -> list[M]:
        """
        Fetch records that satisfy the condition.

        ```python
        t.fetch_where(db, Q.eq(c1=1), dict(c2=True), 10, 5)
        # SQL: SELECT * FROM t WHERE c1 = 1 ORDER BY c2 ASC LIMIT 10 OFFSET 5
        ```

        Args:
            db: The DB connection.
            condition: The query condition.
            orders: An ordering specification, where each key is a column name and each value denotes whether the order is ascending.
            limit: The maximum number of rows to fetch. If `None`, all rows are returned.
            offset: The number of rows to skip.
            lock: A locking statement.
        Returns:
            The model objects.
        """
        wc, wp = where(condition)
        rc, rp = ranged_by(limit, offset)
        s = cls.select()
        c = db.stmt().execute(f"SELECT {s} FROM {cls.name}{_spacer(wc)}{_spacer(order_by(orders))}{_spacer(rc)}{_spacer(lock)}", *(wp + rp))
        return [read_row(row, *s)[0] for row in c.fetchall()]

    @classmethod
    def fetch_one(
        cls: type[M],
        db: Connection,
        condition: Conditional = Q.of(),
        lock: Any | None = None,
    ) -> M | None:
        """
        Fetch a record that satisfies the condition.

        A `ValueError` is raised if multiple records are found.
        Use this method for queries that are certain to return a single row, such as a search by a unique key.

        ```python
        t.fetch_one(db, Q.eq(c1=1))
        # SQL: SELECT * FROM t WHERE c1 = 1
        ```

        Args:
            db: The DB connection.
            condition: The query condition.
            lock: A locking statement.
        Returns:
            A model object if it exists, otherwise `None`.
        Raises:
            ValueError: When multiple records are found.
        """
        rs = cls.fetch_where(db, condition, lock=lock)

        if not rs:
            return None
        elif len(rs) == 1:
            return rs[0]
        else:
            raise ValueError(f"{len(rs)} records are found on the invocation of fetch_one().")

    @classmethod
    def _insert_sql(cls: type[M], record: M | dict[str, Any], qualifier: Mapping[str, Qualifier] = {}) -> tuple[str, list[str], list[Any]]:
        model: M = record if isinstance(record, cls) else cls(**cast(dict, record))
        value_dict = model_values(cls, model)
        check_columns(cls, value_dict)
        cols, vals = list(value_dict.keys()), list(value_dict.values())
        ordered_qs = key_to_index(qualifier, cols)

        def exp(v):
            return lambda i: v

        if any(isinstance(v, Expression) for v in vals):
            key_gen = []
            org_vals = vals
            vals = []
            for v in org_vals:
                if isinstance(v, Expression):
                    key_gen.append(exp(v))
                    vals.extend(v.params)
                else:
                    key_gen.append(lambda i: None)
                    vals.append(v)
            values_clause = values(key_gen, 1, ordered_qs)
        else:
            values_clause = values(len(cols), 1, ordered_qs)

        return f"INSERT INTO {cls.name} ({', '.join(cols)}) VALUES {values_clause}", cols, vals

    @classmethod
    def insert(
        cls: type[M],
        db: Connection,
        record: M | dict[str, Any],
        qualifier: Mapping[str, Qualifier] = {},
        /,
        returning: bool = False,
    ) -> M:
        """
        Insert a record.

        If `returning` is `True` and the DBMS supports the **RETURNING** clause,
        the returned model object contains complete and correct column values.
        Otherwise, an auto-incremental value is set on the returned model object,
        but other column values generated inside the DBMS, such as default values, are not set.

        ```python
        t.insert(db, dict(c1=1, c2=2))
        # SQL: INSERT INTO t (c1, c2) VALUES (1, 2)
        ```

        Args:
            db: The DB connection.
            record: An object containing column values.
            qualifier: Functions that qualify placeholder markers.
            returning: A flag to return the inserted record with complete and correct column values.
        Returns:
            The model of the inserted record.
        """
        model: M = record if isinstance(record, cls) else cls(**cast(dict, record))
        sql, _, vals = cls._insert_sql(record, qualifier)

        if returning:
            if cls.support_returning(db):
                c = db.stmt().execute(f"{sql} RETURNING *", *vals)
                s = cls.select()
                return read_row(c.fetchone(), *s)[0]
            else:
                # Inserted row can't be specified from the table where no primary keys are defined .
                pass

        db.stmt().execute(sql, *vals)
        for c, v in cls.last_sequences(db, 1):
            setattr(model, c.name, v)
        return model

    @classmethod
    def insert_many(
        cls: type[M],
        db: Connection,
        records: list[M | dict[str, Any]],
        qualifier: Mapping[str, Qualifier] = {},
        /,
        returning: bool = False,
    ) -> list[M]:
        """
        Insert records.

        The `returning` flag works differently here than in `insert`.
        When it is `True`, a query to fetch the inserted records is submitted after insertion, and the result is returned.

        Args:
            db: The DB connection.
            records: A list of objects, each containing column values to insert.
            qualifier: Functions that qualify placeholder markers.
            returning: A flag to return the inserted records with complete and correct column values.
        Returns:
            The models of the inserted records.
        """
        if len(records) == 0:
            return []

        models: list[M] = [r if isinstance(r, cls) else cls(**cast(dict, r)) for r in records]

        seq_of_params = []

        sql, cols, params = cls._insert_sql(models[0], qualifier)

        cols = set(cols)
        seq_of_params.append(params)

        for m in models[1:]:
            value_dict = model_values(cls, m)
            check_columns(cls, value_dict, lambda c: c.name in cols, requires_all=True)
            _, _, params = cls._insert_sql(m, qualifier)
            seq_of_params.append(params)

        db.stmt().executemany(sql, seq_of_params)
        num = len(records)
        for c, v in cls.last_sequences(db, num):
            for i, m in enumerate(models):
                setattr(m, c.name, v - (num - i - 1))

        if returning:
            seq_pks = [extract_pks(cls, m) for m in models]
            return cls.fetch_many(db, seq_pks)
        else:
            return models

    @classmethod
    def _update_sql(cls, record: Record, condition: Conditional, qualifier: Mapping[str, Qualifier] = {}, allow_all: bool = True) -> tuple[str, list[str], list[Any]]:
        value_dict = model_values(cls, record, excludes_pk=True)
        check_columns(cls, value_dict)
        cols, vals = list(value_dict.keys()), list(value_dict.values())
        ordered_qs = key_to_index(qualifier, cols)

        def set_col(acc: tuple[list[str], list[Any]], icv: tuple[int, tuple[str, Any]]) -> tuple[list[str], list[Any]]:
            i, (c, v) = icv
            if isinstance(v, Expression):
                clause = f"{c} = {ordered_qs.get(i, lambda x:x)(v.expression)}"
                params = v.params
            else:
                clause = f"{c} = {ordered_qs.get(i, lambda x:x)('$_')}"
                params = [v]
            acc[0].append(clause)
            acc[1].extend(params)
            return acc

        setters, params = reduce(set_col, enumerate(zip(cols, vals)), ([], []))

        wc, wp = where(condition)
        if wc == "" and not allow_all:
            raise ValueError("Update query to update all records is not allowed.")

        return f"UPDATE {cls.name} SET {', '.join(setters)}{_spacer(wc)}", cols, params + wp

    @classmethod
    @overload
    def update(cls, db: Connection, pks: PKS, record: Record, qualifier: Mapping[str, Qualifier] = {},
               /, returning: Literal[False] = False) -> bool: ...
    @classmethod
    @overload
    def update(cls: type[M], db: Connection, pks: PKS, record: Record, qualifier: Mapping[str, Qualifier] = {},
               /, returning: Literal[True] = True) -> M | None: ...
    @classmethod
    def update(
        cls: type[M],
        db: Connection,
        pks: PKS,
        record: Record,
        qualifier: Mapping[str, Qualifier] = {},
        /,
        returning: bool = False,
    ):
        """
        Update a record by primary key(s).

        This method only updates the columns found in `record`, except for the primary key(s).

        ```python
        t.update(db, 1, dict(c1=1, c2=2))
        # SQL: UPDATE t SET c1 = 1, c2 = 2 WHERE id = 1
        ```

        Args:
            db: The DB connection.
            pks: The primary key value(s).
            record: An object containing column values.
            qualifier: Functions that qualify placeholder markers.
            returning: A flag to return the updated record with complete and correct column values.
        Returns:
            The updated record model if `returning` is `True`, otherwise a boolean indicating whether the record exists and was updated.
        """
        cols, vals = parse_pks(cls, pks)
        condition = Conditional.all([Q.eq(**{c: v}) for c, v in zip(cols, vals)])
        if returning:
            if cls.support_returning(db):
                models = cls.update_where(db, record, condition, qualifier, returning=True)
                return models[0] if models else None
            else:
                models = cls.update_where(db, record, condition, qualifier, returning=False)
                return cls.fetch(db, pks)
        else:
            return cls.update_where(db, record, condition, qualifier, returning=False) == 1

    @classmethod
    @overload
    def update_many(cls, db: Connection, records: Sequence[Record], qualifier: Mapping[str, Qualifier] = {},
               /, returning: Literal[False] = False) -> int: ...
    @classmethod
    @overload
    def update_many(cls: type[M], db: Connection, records: Sequence[Record], qualifier: Mapping[str, Qualifier] = {},
               /, returning: Literal[True] = True) -> list[M]: ...
    @classmethod
    def update_many(
        cls,
        db: Connection,
        records: Sequence[Record],
        qualifier: Mapping[str, Qualifier] = {},
        /,
        returning: bool = False,
    ):
        """
        Update records, each identified by its primary key(s).

        This method invokes `executemany`, as defined in DB-API 2.0, instead of invoking `execute` for each record.
        It can improve performance if the DB driver supports optimizations for `executemany`, such as batching.
        On the other hand, the columns to update are determined solely by the first record, and subsequent records must contain values for those columns.
        When inconsistent records are found, a `ValueError` is raised.

        Args:
            db: The DB connection.
            records: A sequence of records. Every record must have primary key value(s) and a consistent set of update column values.
            qualifier: Functions that qualify placeholder markers.
            returning: A flag to return the updated records with complete and correct column values.
        Returns:
            The number of affected rows if `returning` is `False`, otherwise the updated record models.
        Raises:
            ValueError: When some records don't contain required column values.
        """
        if len(records) == 0:
            return [] if returning else 0

        keys = {c.name for c in cls.columns if c.pk}
        if len(keys) == 0:
            raise ValueError(f"update_many is not available because {cls} does not have primary key columns.")

        def classify(acc: tuple[dict[str, Any], dict[str, Any]], cv: tuple[str, Any]):
            if cv[0] in keys:
                acc[0][cv[0]] = cv[1]
            else:
                acc[1][cv[0]] = cv[1]
            return acc

        seq_of_values: list[tuple[dict[str, Any], dict[str, Any]]] = []
        target_columns: set[str] | None = None

        for vs in [model_values(cls, r, excludes_pk=False) for r in records]:
            if not keys < vs.keys():
                raise ValueError(f"Every row must contain values of all primary keys and at least one update column value.")
            pks, rec = reduce(classify, vs.items(), ({}, {}))
            if target_columns is None:
                check_columns(cls, rec)
                target_columns = set(rec.keys())
            else:
                check_columns(cls, rec, lambda c: c.name in target_columns, True) # type: ignore
            seq_of_values.append((pks, rec))

        sql_first = ""
        seq_of_params: list[list[Any]] = []

        for pks, rec in seq_of_values:
            cols, vals = parse_pks(cls, pks)
            condition = Conditional.all([Q.eq(**{c: v}) for c, v in zip(cols, vals)])

            sql, _, params = cls._update_sql(rec, condition, qualifier)
            if not sql_first:
                sql_first = sql
            seq_of_params.append(params)

        if returning:
            db.stmt().executemany(f"{sql_first}", seq_of_params)
            return cls.fetch_many(db, [pks for pks, _ in seq_of_values])
        else:
            return db.stmt().executemany(sql_first, seq_of_params).rowcount

    @classmethod
    @overload
    def update_where(cls, db: Connection, record: Record, condition: Conditional, qualifier: Mapping[str, Qualifier] = {},
                     /, returning: Literal[False] = False, allow_all: bool = False) -> int: ...
    @classmethod
    @overload
    def update_where(cls: type[M], db: Connection, record: Record, condition: Conditional, qualifier: Mapping[str, Qualifier] = {},
                     /, returning: Literal[True] = True, allow_all: bool = False) -> list[M]: ...
    @classmethod
    def update_where(
        cls,
        db: Connection,
        record: Record,
        condition: Conditional,
        qualifier: Mapping[str, Qualifier] = {},
        /,
        returning: bool = False,
        allow_all: bool = True,
    ):
        """
        Update records that satisfy the condition.

        ```python
        t.update_where(db, dict(c2=2), Q.eq(c1=1))
        # SQL: UPDATE t SET c2 = 2 WHERE c1 = 1
        ```

        Args:
            db: The DB connection.
            record: An object containing column values.
            condition: The query condition.
            qualifier: Functions that qualify placeholder markers.
            returning: A flag to return the updated records with complete and correct column values.
            allow_all: If `False`, an empty condition causes a `ValueError` to be raised.
        Returns:
            The number of affected rows if `returning` is `False`, otherwise the updated record models.
        """
        sql, _, params = cls._update_sql(record, condition, qualifier, allow_all)

        if returning:
            if cls.support_returning(db):
                c = db.stmt().execute(f"{sql} RETURNING *", *params)
                s = cls.select()
                return [read_row(row, *s)[0] for row in c.fetchall()]
            else:
                raise NotImplementedError(f"RETURNING is not supported and there is no way to fetch updated rows exactly.")
        else:
            c = db.stmt().execute(sql, *params)

            return c.rowcount

    @classmethod
    @overload
    def delete(cls, db: Connection, pks: PKS, /, returning: Literal[False] = False) -> bool: ...
    @classmethod
    @overload
    def delete(cls: type[M], db: Connection, pks: PKS, /, returning: Literal[True] = True) -> M | None: ...
    @classmethod
    def delete(cls: type[M], db: Connection, pks: PKS, /, returning: bool = False):
        """
        Delete a record by primary key(s).

        ```python
        t.delete(db, 1)
        # SQL: DELETE FROM t WHERE id = 1
        ```

        Args:
            db: The DB connection.
            pks: The primary key value(s).
            returning: A flag to return the deleted record, if any.
        Returns:
            The deleted record model if `returning` is `True`, otherwise a boolean indicating whether the record exists and was deleted.
        """
        cols, vals = parse_pks(cls, pks)

        if returning:
            models = cls.delete_where(db, Conditional.all([Q.eq(**{c: v}) for c, v in zip(cols, vals)]), returning=True)
            return models[0] if models else None
        else:
            return cls.delete_where(db, Conditional.all([Q.eq(**{c: v}) for c, v in zip(cols, vals)])) == 1

    @classmethod
    @overload
    def delete_many(cls, db: Connection, seq_pks: Sequence[PKS] | Sequence[Record], /, returning: Literal[False] = False) -> int: ...
    @overload
    @classmethod
    def delete_many(cls: type[M], db: Connection, seq_pks: Sequence[PKS] | Sequence[Record], /, returning: Literal[True] = True) -> list[M]: ...
    @classmethod
    def delete_many(cls: type[M], db: Connection, seq_pks: Sequence[PKS] | Sequence[Record], /, returning: bool = False):
        """
        Delete records by a set of primary key(s).

        This method invokes `executemany`, as defined in DB-API 2.0, instead of invoking `execute` for each record.
        It can improve performance if the DB driver supports optimizations for `executemany`, such as batching.

        Args:
            db: The DB connection.
            seq_pks: A sequence of primary key value(s).
            returning: A flag to return the deleted records.
        Returns:
            The number of affected rows if `returning` is `False`, otherwise the deleted record models.
        """
        if len(seq_pks) == 0:
            return None

        pks_dicts: list[dict[str, Any]] = []
        for rec in seq_pks:
            if isinstance(rec, (dict, cls)):
                pks_dicts.append(extract_pks(cls, rec))
            else:
                cols, vals = parse_pks(cls, rec)
                pks_dicts.append(dict(zip(cols, vals)))

        condition = Conditional.all([Q.eq(**{c: v}) for c, v in pks_dicts[0].items()])
        wc, wp = where(condition)

        sql = f"DELETE FROM {cls.name}{_spacer(wc)}"
        seq_of_params: list[list[Any]] = [wp]

        for v in pks_dicts[1:]:
            condition = Conditional.all([Q.eq(**{c: v}) for c, v in v.items()])
            _, wp = where(condition)
            seq_of_params.append(wp)

        if returning:
            models = cls.fetch_many(db, pks_dicts)
            db.stmt().executemany(sql, seq_of_params)
            return models
        else:
            return db.stmt().executemany(sql, seq_of_params).rowcount

    @classmethod
    @overload
    def delete_where(cls, db: Connection, condition: Conditional, /, returning: Literal[False] = False, allow_all: bool = True) -> int: ...
    @classmethod
    @overload
    def delete_where(cls: type[M], db: Connection, condition: Conditional, /, returning: Literal[True] = True, allow_all: bool = True) -> list[M]: ...
    @classmethod
    def delete_where(cls: type[M], db: Connection, condition: Conditional, /, returning: bool = False, allow_all: bool = True):
        """
        Delete records that satisfy the condition.

        ```python
        t.delete_where(db, Q.eq(c1=1))
        # SQL: DELETE FROM t WHERE c1 = 1
        ```

        Args:
            db: The DB connection.
            condition: The query condition.
            returning: A flag to return the deleted records.
            allow_all: If `False`, an empty condition causes a `ValueError` to be raised.
        Returns:
            The number of affected rows if `returning` is `False`, otherwise the deleted record models.
        """
        wc, wp = where(condition)
        if wc == "" and not allow_all:
            raise ValueError("Delete query to delete all records is not allowed.")

        sql = f"DELETE FROM {cls.name}{_spacer(wc)}"

        if returning:
            if cls.support_returning(db):
                c = db.stmt().execute(f"{sql} RETURNING *", *wp)
                return [read_row(row, *cls.select())[0] for row in c.fetchall()]
            else:
                current = cls.fetch_where(db, condition)
                c = db.stmt().execute(sql, *wp)
                return current
        else:
            return db.stmt().execute(sql, *wp).rowcount

    @classmethod
    def last_sequences(cls, db: Connection, num: int) -> list[tuple[Column, int]]:
        return []

    @classmethod
    def support_returning(cls, db: Connection) -> bool:
        return False


def _spacer(s):
    return (" " + str(s)) if s else ""