"""
Asyncio version of `pyracmon.mixin`.

This module provides a mixin type that supplies various DB operations to model types as class methods,
using `AsyncConnection` instead of `Connection`.
"""
from collections.abc import Mapping, Sequence
from itertools import batched
from typing import Any, TypeVar, Literal, overload, TYPE_CHECKING
from .connection import AsyncConnection
from .dbapi import acursor
from .model import Column, IModel, Record, parse_pks, extract_pks
from .select import SelectMixin, AliasedColumn, read_row
from .query import Q, Conditional, where
from .clause import ORDER, ranged_by, order_by
from .util import Qualifier, PKS
from ._mixin import _render, _render_many, _insert, _update, _set_sequences, _pk_condition, _pk_condition_many


#----------------------------------------------------------------
# Types.
#----------------------------------------------------------------
if TYPE_CHECKING:
    class AsyncCRUDMixinBase(IModel):
        @classmethod
        async def last_sequences(cls, db: AsyncConnection, num: int) -> list[tuple[Column, int]]:
            """
            Returns the sequential (auto-incremental) values of a table generated by the latest insertion.

            The result contains all sequential columns and their values.
            When the latest query inserts multiple rows, only the last (i.e., largest) value is returned.

            This method should be overridden by another mixin class defined in a `dialect` module.

            Args:
                db: The DB connection.
                num: The number of records inserted by the latest query.
            Returns:
                A list of `(column, value)` pairs.
            """
            ...

        @classmethod
        async def support_returning(cls, db: AsyncConnection) -> bool:
            """
            Checks whether this DBMS supports the **RETURNING** clause.

            Args:
                db: The DB connection.
            Returns:
                Whether this DBMS supports the **RETURNING** clause.
            """
            ...
else:
    class AsyncCRUDMixinBase:
        pass


M = TypeVar('M', bound='AsyncCRUDMixin')
C = TypeVar('C', bound=str | AliasedColumn, covariant=True)


#----------------------------------------------------------------
# Mixin
#----------------------------------------------------------------
class AsyncCRUDMixin(SelectMixin, AsyncCRUDMixinBase):
    """
    Asyncio version of `CRUDMixin`.

    The default mixin providing class methods available on all model types.

    Every method takes the asynchronous DB connection object as its first argument.
    Several methods take the following arguments.

    - `pks`
        - Primary key value(s).
        - A single value is available for a model whose table has just one primary key column.
        - e.g., if the table has a single primary key `id` of type `int`, `1` can be used to specify the row where `id = 1`.
        - e.g., if the table has multiple primary keys `intid` and `strid`, `dict(intid=1, strid="abc")` is a valid argument.
    - `record` / `records`
        - A record can be a model object or a mapping from column names to their values.
        - Only the columns contained in the record are affected by the operation.
        - e.g., when `dict(c1=1, c2="abc")` is passed for insertion, only `c1` and `c2` are set in the INSERT query.
        - e.g., for an UPDATE query, only those columns will be updated.
    - `condition`
        - A query condition that composes the WHERE clause.
        - `pyracmon.query.Q` is a factory class for creating condition objects.
        - When `None` is passed, all rows are subject to the operation.
    - `qualifier`
        - A mapping from column names to functions that qualify their placeholder markers.
        - Details about the qualifier function are described below.
    - `lock`
        - This is a reserved argument for a locking statement, but currently it just works as a postfix appended to the query.
        - The usage will be changed in a future version.

    The qualifier function is typically used to convert or replace a placeholder marker in an INSERT or UPDATE query.
    By default, those queries contain markers like `INSERT INTO t (c1, c2) VALUES (?, ?)` (the `qmark` paramstyle).
    We sometimes need to qualify markers to apply a DB function, a calculation, a type cast, and so on.
    This feature makes that possible, as shown below.

    ```python
    await t.insert(db, dict(c1=1, c2=None), dict(c1=lambda x: f"{x}+1", c2=lambda x: "now()"))
    # SQL: INSERT INTO t (c1, c2) VALUES (?+1, now())
    ```
    """
    @classmethod
    async def count(cls, db: AsyncConnection, condition: Conditional = Q.of()) -> int:
        """
        Count the rows that satisfy the condition.

        ```python
        await t.count(db, Q.eq(c1=1))
        # SQL: SELECT COUNT(*) FROM t WHERE c1 = 1
        ```

        Args:
            db: The DB connection.
            condition: The query condition.
        Returns:
            The number of rows.
        """
        wc, wp = where(condition)
        async with acursor(await db.stmt().execute(f"SELECT COUNT(*) FROM {cls.name}{_spacer(wc)}", *wp)) as c:
            row = await c.fetchone()
            return row[0] # type: ignore

    @classmethod
    async def fetch(cls: type[M], db: AsyncConnection, pks: PKS, lock: Any | None = None) -> M | None:
        """
        Fetch a record by primary key(s).

        ```python
        await t.fetch(db, 1)
        # SQL: SELECT * FROM t WHERE id = 1
        ```

        Args:
            db: The DB connection.
            pks: The primary key value(s).
            lock: A locking statement.
        Returns:
            A model object if it exists, otherwise `None`.
        """
        _, condition = _pk_condition(cls, pks)
        wc, wp = where(condition)
        s = cls.select()
        sql = f"SELECT {s} FROM {cls.name}{_spacer(wc)}{_spacer(lock)}"
        async with acursor(await db.stmt().execute(sql, *wp)) as c:
            row = await c.fetchone()
            return read_row(row, *s)[0] if row else None

    @classmethod
    async def fetch_many(cls: type[M], db: AsyncConnection, seq_pks: Sequence[PKS], lock: Any | None = None, /, per_page: int = 1000) -> list[M]:
        """
        Fetch records by a sequence of primary key(s).

        This method simply concatenates equality conditions on the primary key(s) using the OR operator.

        ```python
        await t.fetch_many(db, [1, 2, 3])
        # SQL: SELECT * FROM t WHERE id = 1 OR id = 2 OR id = 3
        ```

        Args:
            db: The DB connection.
            seq_pks: A sequence of primary key value(s).
            lock: A locking statement.
            per_page: The maximum number of keys per query execution.
        Returns:
            The model objects, in the same order as the given sequence.
        """
        results: dict[Any, M] = {}

        for page_pks in batched(seq_pks, per_page):
            condition = Conditional.any([_pk_condition(cls, pks)[1] for pks in page_pks])
            wc, wp = where(condition)
            s = cls.select()
            sql = f"SELECT {s} FROM {cls.name}{_spacer(wc)}{_spacer(lock)}"
            async with acursor(await db.stmt().execute(sql, *wp)) as c:
                # Order the results according to the order of the given primary keys.
                for row in await c.fetchall():
                    res: M = read_row(row, *s)[0]
                    results[tuple(extract_pks(cls, res).values())] = res

        records: list[M] = []
        for pks in seq_pks:
            key = tuple(parse_pks(cls, pks)[1])
            if key in results:
                records.append(results[key])

        return records

    @classmethod
    async def fetch_where(
        cls: type[M],
        db: AsyncConnection,
        condition: Conditional = Q.of(),
        orders: Mapping[C, ORDER] = {},
        limit: int | None = None,
        offset: int | None = None,
        lock: Any | None = None,
    ) -> list[M]:
        """
        Fetch records that satisfy the condition.

        ```python
        await t.fetch_where(db, Q.eq(c1=1), dict(c2=True), 10, 5)
        # SQL: SELECT * FROM t WHERE c1 = 1 ORDER BY c2 ASC LIMIT 10 OFFSET 5
        ```

        Args:
            db: The DB connection.
            condition: The query condition.
            orders: An ordering specification, where each key is a column name and each value denotes whether the order is ascending.
            limit: The maximum number of rows to fetch. If `None`, all rows are returned.
            offset: The number of rows to skip.
            lock: A locking statement.
        Returns:
            The model objects.
        """
        wc, wp = where(condition)
        rc, rp = ranged_by(limit, offset)
        s = cls.select()
        sql = f"SELECT {s} FROM {cls.name}{_spacer(wc)}{_spacer(order_by(orders))}{_spacer(rc)}{_spacer(lock)}"
        async with acursor(await db.stmt().execute(sql, *(wp + rp))) as c:
            return [read_row(row, *s)[0] for row in await c.fetchall()]

    @classmethod
    async def fetch_one(
        cls: type[M],
        db: AsyncConnection,
        condition: Conditional = Q.of(),
        lock: Any | None = None,
    ) -> M | None:
        """
        Fetch a record that satisfies the condition.

        A `ValueError` is raised if multiple records are found.
        Use this method for queries that are certain to return a single row, such as a search by a unique key.

        ```python
        await t.fetch_one(db, Q.eq(c1=1))
        # SQL: SELECT * FROM t WHERE c1 = 1
        ```

        Args:
            db: The DB connection.
            condition: The query condition.
            lock: A locking statement.
        Returns:
            A model object if it exists, otherwise `None`.
        Raises:
            ValueError: When multiple records are found.
        """
        rs = await cls.fetch_where(db, condition, lock=lock)

        if not rs:
            return None
        elif len(rs) == 1:
            return rs[0]
        else:
            raise ValueError(f"{len(rs)} records are found on the invocation of fetch_one().")

    @classmethod
    async def insert(
        cls: type[M],
        db: AsyncConnection,
        record: M | dict[str, Any],
        qualifier: Mapping[str, Qualifier] = {},
        /,
        returning: bool = False,
    ) -> M:
        """
        Insert a record.

        If `returning` is `True` and the DBMS supports the **RETURNING** clause,
        the returned model object contains complete and correct column values.
        Otherwise, an auto-incremental value is set on the returned model object,
        but other column values generated inside the DBMS, such as default values, are not set.

        ```python
        await t.insert(db, dict(c1=1, c2=2))
        # SQL: INSERT INTO t (c1, c2) VALUES (1, 2)
        ```

        Args:
            db: The DB connection.
            record: An object containing column values.
            qualifier: Functions that qualify placeholder markers.
            returning: A flag to return the inserted record with complete and correct column values.
        Returns:
            The model of the inserted record.
        """
        model, expressions, vals = _render(cls, record, qualifier)
        sql = _insert(cls, expressions)

        print(sql, vals)
        if returning:
            if await cls.support_returning(db):
                async with acursor(await db.stmt().execute(f"{sql} RETURNING *", *vals)) as c:
                    s = cls.select()
                    return read_row(await c.fetchone(), *s)[0]
            else:
                # Inserted row can't be specified from the table where no primary keys are defined .
                pass

        async with acursor(await db.stmt().execute(sql, *vals)):
            sequences = await cls.last_sequences(db, 1)
            _set_sequences([model], sequences)
            return model

    @classmethod
    async def insert_many(
        cls: type[M],
        db: AsyncConnection,
        records: list[M | dict[str, Any]],
        qualifier: Mapping[str, Qualifier] = {},
        /,
        returning: bool = False,
    ) -> list[M]:
        """
        Insert records.

        The `returning` flag works differently here than in `insert`.
        When it is `True`, a query to fetch the inserted records is submitted after insertion, and the result is returned.

        Args:
            db: The DB connection.
            records: A list of objects, each containing column values to insert.
            qualifier: Functions that qualify placeholder markers.
            returning: A flag to return the inserted records with complete and correct column values.
        Returns:
            The models of the inserted records.
        """
        if len(records) == 0:
            return []

        models, expression, all_params = _render_many(cls, records, qualifier)
        sql = _insert(cls, expression)

        async with acursor(await db.stmt().executemany(sql, all_params)) as c:
            num = len(records)
            sequences = await cls.last_sequences(db, num)
            _set_sequences(models, sequences)

        if returning:
            seq_pks = [extract_pks(cls, m) for m in models]
            return await cls.fetch_many(db, seq_pks)
        else:
            return models

    @classmethod
    @overload
    async def update(cls, db: AsyncConnection, pks: PKS, record: Record, qualifier: Mapping[str, Qualifier] = {},
               /, returning: Literal[False] = False) -> bool: ...
    @classmethod
    @overload
    async def update(cls: type[M], db: AsyncConnection, pks: PKS, record: Record, qualifier: Mapping[str, Qualifier] = {},
               /, returning: Literal[True] = True) -> M | None: ...
    @classmethod
    async def update(
        cls: type[M],
        db: AsyncConnection,
        pks: PKS,
        record: Record,
        qualifier: Mapping[str, Qualifier] = {},
        /,
        returning: bool = False,
    ):
        """
        Update a record by primary key(s).

        This method only updates the columns found in `record`, except for the primary key(s).

        ```python
        await t.update(db, 1, dict(c1=1, c2=2))
        # SQL: UPDATE t SET c1 = 1, c2 = 2 WHERE id = 1
        ```

        Args:
            db: The DB connection.
            pks: The primary key value(s).
            record: An object containing column values.
            qualifier: Functions that qualify placeholder markers.
            returning: A flag to return the updated record with complete and correct column values.
        Returns:
            The updated record model if `returning` is `True`, otherwise a boolean indicating whether the record exists and was updated.
        """
        _, condition = _pk_condition(cls, pks)
        if returning:
            if await cls.support_returning(db):
                models = await cls.update_where(db, record, condition, qualifier, returning=True)
                return models[0] if models else None
            else:
                await cls.update_where(db, record, condition, qualifier, returning=False)
                return await cls.fetch(db, pks)
        else:
            return await cls.update_where(db, record, condition, qualifier, returning=False) == 1

    @classmethod
    @overload
    async def update_many(cls, db: AsyncConnection, records: Sequence[Record], qualifier: Mapping[str, Qualifier] = {},
               /, returning: Literal[False] = False) -> int: ...
    @classmethod
    @overload
    async def update_many(cls: type[M], db: AsyncConnection, records: Sequence[Record], qualifier: Mapping[str, Qualifier] = {},
               /, returning: Literal[True] = True) -> list[M]: ...
    @classmethod
    async def update_many(
        cls,
        db: AsyncConnection,
        records: Sequence[Record],
        qualifier: Mapping[str, Qualifier] = {},
        /,
        returning: bool = False,
    ):
        """
        Update records, each identified by its primary key(s).

        This method invokes `executemany`, as defined in DB-API 2.0, instead of invoking `execute` for each record.
        It can improve performance if the DB driver supports optimizations for `executemany`, such as batching.
        On the other hand, the columns to update are determined solely by the first record, and subsequent records must contain values for those columns.
        When inconsistent records are found, a `ValueError` is raised.

        Args:
            db: The DB connection.
            records: A sequence of records. Every record must have primary key value(s) and a consistent set of update column values.
            qualifier: Functions that qualify placeholder markers.
            returning: A flag to return the updated records with complete and correct column values.
        Returns:
            The number of affected rows if `returning` is `False`, otherwise the updated record models.
        Raises:
            ValueError: When some records don't contain required column values.
        """
        if len(records) == 0:
            return [] if returning else 0

        if not any(c.pk for c in cls.columns):
            raise ValueError(f"update_many is not available because {cls} does not have primary key columns.")

        models, expressions, upd_params = _render_many(cls, records, qualifier, excludes_pk=True)
        if len(expressions) == 0:
            raise ValueError(f"No column values are found to update.")

        sql = _update(cls, expressions)

        wc, all_pks, pk_params, _ = _pk_condition_many(cls, records)
        sql += _spacer(wc)

        all_params = [upd+pk for upd, pk in zip(upd_params, pk_params)]

        if returning:
            async with acursor(await db.stmt().executemany(f"{sql}", all_params)) as c:
                return await cls.fetch_many(db, all_pks)
        else:
            async with acursor(await db.stmt().executemany(f"{sql}", all_params)) as c:
                return c.rowcount

    @classmethod
    @overload
    async def update_where(cls, db: AsyncConnection, record: Record, condition: Conditional, qualifier: Mapping[str, Qualifier] = {},
                     /, returning: Literal[False] = False, allow_all: bool = False) -> int: ...
    @classmethod
    @overload
    async def update_where(cls: type[M], db: AsyncConnection, record: Record, condition: Conditional, qualifier: Mapping[str, Qualifier] = {},
                     /, returning: Literal[True] = True, allow_all: bool = False) -> list[M]: ...
    @classmethod
    async def update_where(
        cls,
        db: AsyncConnection,
        record: Record,
        condition: Conditional,
        qualifier: Mapping[str, Qualifier] = {},
        /,
        returning: bool = False,
        allow_all: bool = True,
    ):
        """
        Update records that satisfy the condition.

        ```python
        await t.update_where(db, dict(c2=2), Q.eq(c1=1))
        # SQL: UPDATE t SET c2 = 2 WHERE c1 = 1
        ```

        Args:
            db: The DB connection.
            record: An object containing column values.
            condition: The query condition.
            qualifier: Functions that qualify placeholder markers.
            returning: A flag to return the updated records with complete and correct column values.
            allow_all: If `False`, an empty condition causes a `ValueError` to be raised.
        Returns:
            The number of affected rows if `returning` is `False`, otherwise the updated record models.
        """
        _, expressions, params = _render(cls, record, qualifier, excludes_pk=True)
        sql = _update(cls, expressions)

        wc, wp = where(condition)
        if wc == "" and not allow_all:
            raise ValueError("Update query to update all records is not allowed.")
        if wc:
            sql += _spacer(wc)
            params += wp

        if returning:
            if await cls.support_returning(db):
                async with acursor(await db.stmt().execute(f"{sql} RETURNING *", *params)) as c:
                    s = cls.select()
                    return [read_row(row, *s)[0] for row in await c.fetchall()]
            else:
                raise NotImplementedError(f"RETURNING is not supported and there is no way to fetch updated rows exactly.")
        else:
            async with acursor(await db.stmt().execute(sql, *params)) as c:
                return c.rowcount

    @classmethod
    @overload
    async def delete(cls, db: AsyncConnection, pks: PKS, /, returning: Literal[False] = False) -> bool: ...
    @classmethod
    @overload
    async def delete(cls: type[M], db: AsyncConnection, pks: PKS, /, returning: Literal[True] = True) -> M | None: ...
    @classmethod
    async def delete(cls: type[M], db: AsyncConnection, pks: PKS, /, returning: bool = False):
        """
        Delete a record by primary key(s).

        ```python
        await t.delete(db, 1)
        # SQL: DELETE FROM t WHERE id = 1
        ```

        Args:
            db: The DB connection.
            pks: The primary key value(s).
            returning: A flag to return the deleted record, if any.
        Returns:
            The deleted record model if `returning` is `True`, otherwise a boolean indicating whether the record exists and was deleted.
        """
        _, condition = _pk_condition(cls, pks)
        if returning:
            models = await cls.delete_where(db, condition, returning=True)
            return models[0] if models else None
        else:
            return await cls.delete_where(db, condition) == 1

    @classmethod
    @overload
    async def delete_many(cls, db: AsyncConnection, seq_pks: Sequence[PKS] | Sequence[Record], /, returning: Literal[False] = False) -> int: ...
    @overload
    @classmethod
    async def delete_many(cls: type[M], db: AsyncConnection, seq_pks: Sequence[PKS] | Sequence[Record], /, returning: Literal[True] = True) -> list[M]: ...
    @classmethod
    async def delete_many(cls: type[M], db: AsyncConnection, seq_pks: Sequence[PKS] | Sequence[Record], /, returning: bool = False):
        """
        Delete records by a set of primary key(s).

        This method invokes `executemany`, as defined in DB-API 2.0, instead of invoking `execute` for each record.
        It can improve performance if the DB driver supports optimizations for `executemany`, such as batching.

        Args:
            db: The DB connection.
            seq_pks: A sequence of primary key value(s).
            returning: A flag to return the deleted records.
        Returns:
            The number of affected rows if `returning` is `False`, otherwise the deleted record models.
        """
        if len(seq_pks) == 0:
            return 0 if returning else []

        wc, all_pks, all_params, _ = _pk_condition_many(cls, seq_pks)
        sql = f"DELETE FROM {cls.name}{_spacer(wc)}"

        if returning:
            models = await cls.fetch_many(db, all_pks)
            async with acursor(await db.stmt().executemany(sql, all_params)):
                return models
        else:
            async with acursor(await db.stmt().executemany(sql, all_params)) as c:
                return c.rowcount

    @classmethod
    @overload
    async def delete_where(cls, db: AsyncConnection, condition: Conditional, /, returning: Literal[False] = False, allow_all: bool = True) -> int: ...
    @classmethod
    @overload
    async def delete_where(cls: type[M], db: AsyncConnection, condition: Conditional, /, returning: Literal[True] = True, allow_all: bool = True) -> list[M]: ...
    @classmethod
    async def delete_where(cls: type[M], db: AsyncConnection, condition: Conditional, /, returning: bool = False, allow_all: bool = True):
        """
        Delete records that satisfy the condition.

        ```python
        await t.delete_where(db, Q.eq(c1=1))
        # SQL: DELETE FROM t WHERE c1 = 1
        ```

        Args:
            db: The DB connection.
            condition: The query condition.
            returning: A flag to return the deleted records.
            allow_all: If `False`, an empty condition causes a `ValueError` to be raised.
        Returns:
            The number of affected rows if `returning` is `False`, otherwise the deleted record models.
        """
        wc, wp = where(condition)
        if wc == "" and not allow_all:
            raise ValueError("Delete query to delete all records is not allowed.")

        sql = f"DELETE FROM {cls.name}{_spacer(wc)}"

        if returning:
            if await cls.support_returning(db):
                async with acursor(await db.stmt().execute(f"{sql} RETURNING *", *wp)) as c:
                    return [read_row(row, *cls.select())[0] for row in await c.fetchall()]
            else:
                current = await cls.fetch_where(db, condition)
                async with acursor(await db.stmt().execute(sql, *wp)) as c:
                    return current
        else:
            async with acursor(await db.stmt().execute(sql, *wp)) as c:
                return c.rowcount

    @classmethod
    async def last_sequences(cls, db: AsyncConnection, num: int) -> list[tuple[Column, int]]:
        return []

    @classmethod
    async def support_returning(cls, db: AsyncConnection) -> bool:
        return False


def _spacer(s):
    return (" " + str(s)) if s else ""
