[build-system]
requires = ["uv_build>=0.9.17,<0.10.0"]
build-backend = "uv_build"

[project]
name = "pyracmon"
version = "1.1.0.dev1"
authors = [
  { name="sozuberry", email="sozuberry@gmail.com" },
]
description = "Python O/R Mapping extension for DB-API 2.0"
readme = "README.md"
license-files = ["LICENSE"]
requires-python = ">=3.12"
classifiers = [
    "Programming Language :: Python :: 3.12",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
  "typing_extensions",
]

[dependency-groups]
dev = [
  "pytest",
  "psycopg2-binary",
  "PyMySQL",
  "pytest-asyncio>=1.4.0",
  "psycopg[binary]>=3.3.4",
]

[project.urls]
"Homepage" = "https://github.com/sozu/py-pyracmon"

[tool.uv.build-backend]
module-root = ""
